# Generated by Django 5.2 on 2025-04-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todolist_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='descriptions',
            new_name='description',
        ),
    ]
